### ISSUE TITLE
Changing ports

### ISSUE THREAD

**Issue by twoenter** [dnpwwo/Domoticz-Google-Plugin#13]
Hi! 

Using this plugin on domoticz beta and a Synology NAS and it is working perfectly. Thank you for your good work!

I have a issue/feature request. For voice notifications the plugin uses almost every time a different port to access the mp3 file. When I add this port to the synology firewall the chromecast does play the audio file without any problem. When the port changes the port is blocked by the firewall and the file is not accessible anymore. So I have to edit the firewall each time.

Is it possible to use 1 port, or a specified range which is editable from plugin settings?

Thank you,

Wouter

**Comment by dnpwwo** [comment]
@twoenter,

Not through configuration but you could change it yourself.

Line 387:
`ipPort = str(random.randint(10001,19999))`
controls the port range for serving voice messages.  You could try shrinking the range, there's no reason that wouldn't work that I know of.

Thanks for the feedback :)

**Comment by twoenter** [comment]
Ok thank you!
