### ISSUE TITLE
[REQUEST] Manually specify chromecast devices

### ISSUE THREAD

**Issue by Want100Cookies** [dnpwwo/Domoticz-Google-Plugin#28]
Hello,

I am running this plugin inside docker behind a reverse proxy. I wat to control some local chromecast devices using this plugin but because the docker container is behind a bridge network (I intent to keep it this way, host-network is not a option) auto-discovery is not working. 

Is it perhaps possible to add chrome-cast devices manually?
Is it also possible to specify on which endpoint the plugin should listen? The IP address from the log-file is the internal IP from within docker and that would not work if the chromecast were to connect to that.

Thanks in advance!

**Comment by sincze** [comment]
+1 
I would like to add discovery also not working for Chromecasts that sit in my spare IOT vlan.

**Comment by dnpwwo** [comment]
Unfortunately this is not possible without a complete re-write.

I used an existing library to handle all the comms and messages so I don't currently even store the Google device details, just the UUID so I can identify them consistently.

Sorry
