### ISSUE TITLE
Resume what was streamed before the notification

### ISSUE THREAD

**Issue by rezzalex** [dnpwwo/Domoticz-Google-Plugin#31]
Hello,

Would it be possible to ask the notification targeted Google Speaker to resume its previous streaming web radio (or anything else) after receiving the message from Domoticz?

**Comment by dnpwwo** [comment]
Sadly (last time I checked) the Google API doesn't have any support for this which is annoying because I wanted to do this as well.

They have not exposed the 'Broadcast' function.

**Comment by rezzalex** [comment]
What about scripting a "play" Script Commands after sending a notification ?
Even better, automatize it ?

**Comment by rezzalex** [comment]
> What about scripting a "play" Script Commands after sending a notification ?
> Even better, automatize it ?

@dnpwwo , would you have recommendations ?

For information, a project called "Google Assistant relay " allow to broadcast to a specific device or room.

Thanks
