### ISSUE TITLE
discoveryCallback: 'Chromecast' object has no attribute 'Model'

### ISSUE THREAD

**Issue by lemassykoi** [dnpwwo/Domoticz-Google-Plugin#45]
Hi, I use this Google device : 

![image](https://user-images.githubusercontent.com/16377344/215921295-a75ce919-63ae-4c5f-84f9-814e16f54880.png)

```
2023-02-01 01:05:24.386 Error: GTTS: discoveryCallback: 'Chromecast' object has no attribute 'Model'
2023-02-01 01:05:24.386 Error: GTTS: <class 'AttributeError'>: plugin.py at 493
```

and I got this error when installed plugin, **but all is working fine.** (notification sub system)

Just to let you know. Thanks.

**Comment by dnpwwo** [comment]
Thanks for reporting.

Fixed.

**Comment by dnpwwo** [comment]
2.0.4
